esphome:
  name: water-heater-monitor
  friendly_name: water-heater-monitor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
spi:
  miso_pin: GPIO12
  clk_pin: GPIO14

sensor:
  - platform: max6675
    name: "Upper tank temp"
    cs_pin: GPIO16
    update_interval: 1s
  - platform: max6675
    name: "Lower tank temp"
    cs_pin: GPIO0
    update_interval: 1s